export const USER = Object.freeze({
    SET_CURRENT_USER : "SET_CURRENT_USER"
});

export const CART = Object.freeze({
    TOOGLE_CART_HIDDEN: "TOOGLE_CART_HIDDEN",
    ADD_ITEM: "ADD_ITEM",
    REMOVE_ITEM: "REMOVE_ITEM",
    REDUCE_QUANTITY: "REDUCE_QUANTITY"
});

export const SHOP = Object.freeze({
    FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',
    FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
    FETCH_COLLECTIONS_ERROR: 'FETCH_COLLECTIONS_ERROR'
});