export const USER = Object.freeze({
    GOOGLE_SIGIN_START: "GOOGLE_SIGIN_START",
    EMAIL_SIGIN_START: "EMAIL_SIGIN_START",
    SIGIN_SUCCESS: "SIGIN_SUCCESS",
    SIGIN_FAILURE: "SIGIN_FAILURE",
    CHECK_USER_SESSION: "CHECK_USER_SESSION",
    SIGN_OUT_START: "SIGN_OUT_START",
    SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
    SIGN_OUT_FAILURE: "SIGN_OUT_FAILURE",
    SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
    SIGN_UP_FAILURE: "SIGN_UP_FAILURE",
    SIGN_UP_START: "SIGN_UP_START"
});

export const CART = Object.freeze({
    TOOGLE_CART_HIDDEN: "TOOGLE_CART_HIDDEN",
    ADD_ITEM: "ADD_ITEM",
    REMOVE_ITEM: "REMOVE_ITEM",
    REDUCE_QUANTITY: "REDUCE_QUANTITY",
    CLEAR_CART: "CLEAR_CART"
});

export const SHOP = Object.freeze({
    FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',
    FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
    FETCH_COLLECTIONS_ERROR: 'FETCH_COLLECTIONS_ERROR'
});